// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_Zl_fAHyKKpvtk6eSe9UteuCkUk9Et4',
    appId: '1:213230951147:web:b98bd787a3b3cee3237cae',
    messagingSenderId: '213230951147',
    projectId: 'practical-flutter-crud-ca259',
    authDomain: 'practical-flutter-crud-ca259.firebaseapp.com',
    storageBucket: 'practical-flutter-crud-ca259.firebasestorage.app',
    measurementId: 'G-20KM36Z70N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_z2rgHIR_TB9OneONppTq9CX4i8L3vE',
    appId: '1:213230951147:android:fa6843d6c0589879237cae',
    messagingSenderId: '213230951147',
    projectId: 'practical-flutter-crud-ca259',
    storageBucket: 'practical-flutter-crud-ca259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQDPp6CWrO_pLkwx3uZTS9rI_fC7ZyHWg',
    appId: '1:213230951147:ios:a55192209b1b746b237cae',
    messagingSenderId: '213230951147',
    projectId: 'practical-flutter-crud-ca259',
    storageBucket: 'practical-flutter-crud-ca259.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );
}
